version: '3'
services:
  gastby:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: ./entrypoint.sh
    ports:
      - "1234:9000"
    volumes:
      - .:/app
      - /app/node_modules